/**
 * PostgreSQL for one environment.
 *
 * Private subnets only, reachable exclusively from the security groups passed
 * in. There is no public endpoint and no bastion: getting a shell on the
 * database means going through ECS Exec on a task that already has access.
 *
 * The master password is generated and stored by RDS itself
 * (`manage_master_user_password`), so it is never in Terraform state, never in
 * a variable, and never in a plan output. Rotation is handled by Secrets
 * Manager rather than by hand.
 */

resource "aws_db_subnet_group" "this" {
  name        = "${var.name_prefix}-db"
  description = "Private subnets for ${var.name_prefix} Postgres"
  subnet_ids  = var.private_subnet_ids

  tags = merge(var.tags, { Name = "${var.name_prefix}-db" })
}

resource "aws_security_group" "this" {
  name        = "${var.name_prefix}-db"
  description = "Postgres access for ${var.name_prefix}"
  vpc_id      = var.vpc_id

  tags = merge(var.tags, { Name = "${var.name_prefix}-db" })

  lifecycle {
    create_before_destroy = true
  }
}

# count, not for_each: the client security group ids come from another module
# and are unknown at plan time, which for_each cannot handle. The list length
# is known, so count plans cleanly.
resource "aws_vpc_security_group_ingress_rule" "postgres" {
  count = length(var.client_security_group_ids)

  security_group_id            = aws_security_group.this.id
  description                  = "Postgres from an approved client security group"
  from_port                    = 5432
  to_port                      = 5432
  ip_protocol                  = "tcp"
  referenced_security_group_id = var.client_security_group_ids[count.index]

  tags = var.tags
}

# No egress rules. A database has no business initiating outbound connections.

resource "aws_db_parameter_group" "this" {
  name_prefix = "${var.name_prefix}-pg16-"
  family      = "postgres16"
  description = "Logging and statement tuning for ${var.name_prefix}"

  # Reject any connection that is not using TLS. The application already
  # connects with the RDS CA bundle, so this closes the door rather than
  # trusting every client to do the right thing.
  parameter {
    name  = "rds.force_ssl"
    value = "1"
  }

  parameter {
    name  = "log_min_duration_statement"
    value = tostring(var.log_min_duration_ms)
  }

  # Enough context to trace a slow query back to a request.
  parameter {
    name  = "log_connections"
    value = "1"
  }

  parameter {
    name  = "log_disconnections"
    value = "1"
  }

  parameter {
    name  = "log_lock_waits"
    value = "1"
  }

  # The allocation path takes row locks; a stuck one should show up in the log
  # rather than as an unexplained timeout.
  parameter {
    name  = "deadlock_timeout"
    value = "1000"
  }

  parameter {
    name  = "pg_stat_statements.track"
    value = "ALL"
  }

  parameter {
    name         = "shared_preload_libraries"
    value        = "pg_stat_statements"
    apply_method = "pending-reboot"
  }

  tags = var.tags

  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_db_instance" "this" {
  identifier = "${var.name_prefix}-postgres"

  engine         = "postgres"
  engine_version = var.engine_version
  instance_class = var.instance_class

  allocated_storage     = var.allocated_storage
  max_allocated_storage = var.max_allocated_storage
  storage_type          = "gp3"
  storage_encrypted     = true

  db_name  = var.database_name
  username = var.master_username

  # Password lives in Secrets Manager, generated by RDS. Never in state.
  manage_master_user_password = true

  db_subnet_group_name   = aws_db_subnet_group.this.name
  vpc_security_group_ids = [aws_security_group.this.id]
  parameter_group_name   = aws_db_parameter_group.this.name
  publicly_accessible    = false
  port                   = 5432

  # Costs nothing and leaves the door open to dropping the static password
  # later in favour of short-lived IAM tokens.
  iam_database_authentication_enabled = true

  multi_az                = var.multi_az
  backup_retention_period = var.backup_retention_days
  backup_window           = var.backup_window
  maintenance_window      = var.maintenance_window
  copy_tags_to_snapshot   = true

  auto_minor_version_upgrade = true
  apply_immediately          = false

  deletion_protection       = var.deletion_protection
  skip_final_snapshot       = var.skip_final_snapshot
  final_snapshot_identifier = var.skip_final_snapshot ? null : "${var.name_prefix}-final-${formatdate("YYYYMMDDhhmmss", timestamp())}"

  performance_insights_enabled          = var.performance_insights_enabled
  performance_insights_retention_period = var.performance_insights_enabled ? 7 : null

  enabled_cloudwatch_logs_exports = ["postgresql", "upgrade"]

  tags = merge(var.tags, { Name = "${var.name_prefix}-postgres" })

  lifecycle {
    # The snapshot name embeds a timestamp, which would otherwise show as a
    # diff on every plan.
    ignore_changes = [final_snapshot_identifier]
  }
}

# --- Alarms ----------------------------------------------------------------

resource "aws_cloudwatch_metric_alarm" "cpu" {
  alarm_name          = "${var.name_prefix}-db-cpu-high"
  alarm_description   = "Database CPU above 80 percent"
  namespace           = "AWS/RDS"
  metric_name         = "CPUUtilization"
  statistic           = "Average"
  comparison_operator = "GreaterThanThreshold"
  threshold           = 80
  period              = 300
  evaluation_periods  = 2
  treat_missing_data  = "notBreaching"

  dimensions = {
    DBInstanceIdentifier = aws_db_instance.this.identifier
  }

  alarm_actions = var.alarm_actions
  ok_actions    = var.alarm_actions

  tags = var.tags
}

resource "aws_cloudwatch_metric_alarm" "storage" {
  alarm_name          = "${var.name_prefix}-db-storage-low"
  alarm_description   = "Less than 2 GB of free storage"
  namespace           = "AWS/RDS"
  metric_name         = "FreeStorageSpace"
  statistic           = "Average"
  comparison_operator = "LessThanThreshold"
  threshold           = 2 * 1024 * 1024 * 1024
  period              = 300
  evaluation_periods  = 1
  treat_missing_data  = "notBreaching"

  dimensions = {
    DBInstanceIdentifier = aws_db_instance.this.identifier
  }

  alarm_actions = var.alarm_actions

  tags = var.tags
}

/**
 * Connection ceiling.
 *
 * Postgres derives max_connections from instance memory, and the API opens a
 * pool per task. Autoscaling to six tasks multiplies that pool, which is the
 * realistic way this database runs out of connections.
 */
resource "aws_cloudwatch_metric_alarm" "connections" {
  alarm_name          = "${var.name_prefix}-db-connections-high"
  alarm_description   = "Connection count approaching the instance limit"
  namespace           = "AWS/RDS"
  metric_name         = "DatabaseConnections"
  statistic           = "Maximum"
  comparison_operator = "GreaterThanThreshold"
  threshold           = 60
  period              = 300
  evaluation_periods  = 2
  treat_missing_data  = "notBreaching"

  dimensions = {
    DBInstanceIdentifier = aws_db_instance.this.identifier
  }

  alarm_actions = var.alarm_actions

  tags = var.tags
}
